# Database Configuration
spring.datasource.url=jdbc:postgresql://viaduct.proxy.rlwy.net:49096/railway
spring.datasource.username=postgres
spring.datasource.password=rZrXcPAdlEKMxKxTLXiMNpPhYjoqyuyt
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.error.include-stacktrace=never